import { Link, useLocation } from 'react-router-dom';
import { ArrowRight, CloudSun, Waves, ShieldCheck } from 'lucide-react';
const content:Record<string,[string,string,string]>={
 warnings:['WARNINGS & PREPAREDNESS','Know what’s ahead.\nPrepare with confidence.','Find your coastal district, understand the information available, and follow official local guidance.'],
 command:['YOUR COAST. YOUR WEATHER.','A clearer forecast.\nA better prepared coast.','Understand tropical cyclones with accessible maps, weather observations and the context behind each forecast.'],
 live:['OCEAN & ATMOSPHERE','See the conditions\nshaping our weather.','Explore ocean temperature, winds and moisture together to understand the environment around a storm.'],
 forecast:['TRACK & INTENSITY','Follow the path.\nUnderstand the possibilities.','Explore the forecast alongside its uncertainty. A predicted track is a range of possibilities, not a promise.'],
 historical:['THE STORM ARCHIVE','Past storms.\nLasting lessons.','Explore historical cyclone records and learn how storms have changed across our oceans.']
};
export function PublicHero(){const {pathname}=useLocation();const key=pathname.split('/').filter(Boolean).pop()||'command';const copy=content[key]||['CYCLONE AI / COASTAL INTELLIGENCE','Weather information.\nMade easier to understand.','Explore the observations, research and tools that help put tropical cyclone information in context.'];return <section className="public-hero"><div className="hero-copy"><span className="hero-kicker"><CloudSun size={17}/>{copy[0]}</span><h1>{copy[1]}</h1><p>{copy[2]}</p><div className="hero-actions"><Link to={key==='warnings'?'#district-directory':'/dashboard/warnings'} onClick={key==='warnings'?e=>{e.preventDefault();document.getElementById('district-directory')?.scrollIntoView({behavior:'smooth'});}:undefined}>{key==='warnings'?'Find your district':'Explore warnings & safety'}<ArrowRight size={16}/></Link><a href="https://rsmcnewdelhi.imd.gov.in/" target="_blank" rel="noreferrer">Read official advisories ↗</a></div></div><div className="hero-caption"><Waves size={18}/><span>North Indian Ocean<small>Bay of Bengal & Arabian Sea</small></span><span className="decorative-label">Illustrative atmosphere</span></div><div className="hero-trust"><ShieldCheck size={15}/><span>Independent research platform · Official warnings are issued by IMD and local authorities.</span></div></section>}
