import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, Search, MapPin, Info, Radio, Backpack, House, RefreshCw } from 'lucide-react';
import { fetchCoastalDistrictRoster, fetchDistrictRiskAnalysis, fetchStrikeVerification, type StrikeVerificationResponse } from '../services/riskService';
import { DashboardHero } from '../components/layout/DashboardHero';
import { fetchHistoricalCatalog } from '../services/historicalService';
import type { HistoricalStormSummary } from '../types/historical';
import { useCyclone } from '../hooks/useCyclone';
import type { GISRiskAnalysisResult, District, DetailedDistrictRisk } from '../types/risk';
import { fmtDateIST, fmtTime as fmtISTUTC } from '../utils/dataAge';
const pct=(v:number|null|undefined)=>v==null?'—':`${Math.round(100*v)}%`;
const fmtTime=(iso?:string)=>iso?fmtISTUTC(iso,{year:true}):'';
const stormLabel=(s:HistoricalStormSummary)=>`${s.name} (${fmtDateIST(s.landfallDate,{year:true,day:false})}, ${s.peakIMDGrade})`;
const actualText=(a?:DetailedDistrictRisk)=>!a||a.actualHit==null?'—':a.actualHit?`Hit · ${a.actualDistanceKm} km at +${a.actualHour} h`:`Not hit · closest ${a.actualDistanceKm} km`;
const tiers=[{key:'RED',title:'Red',label:'50% or higher strike chance',description:'The storm centre is more likely than not to pass within 100 km in the next 24 h. Read the official advisory and follow local authorities.'},{key:'ORANGE',title:'Orange',label:'25-50% strike chance',description:'A real possibility of the storm centre passing within 100 km in 24 h. Review household plans and keep checking official updates.'},{key:'YELLOW',title:'Yellow',label:'10-25% strike chance',description:'The storm could come close. Stay informed about changing conditions.'}];
export default function WarningsImpact({variant='live'}:{variant?:'live'|'test'}){
 const isTest=variant==='test';
 const {cyclone}=useCyclone();const [roster,setRoster]=useState<District[]>([]);const [risk,setRisk]=useState<GISRiskAnalysisResult|null>(null);const [loading,setLoading]=useState(true);const [search,setSearch]=useState('');const [state,setState]=useState('ALL');const [level,setLevel]=useState('ALL');const [refresh,setRefresh]=useState(0);
 // which storm: 'LIVE' (the current storm) or a 2021-23 or 2025 test storm from the replay set, at a chosen forecast step
 const [catalog,setCatalog]=useState<HistoricalStormSummary[]>([]);const [source,setSource]=useState(isTest?'':'LIVE');const [step,setStep]=useState(0);const [verif,setVerif]=useState<StrikeVerificationResponse|null>(null);
 const testStorm=catalog.find(s=>s.id===source);
 useEffect(()=>{if(!isTest)return;void fetchHistoricalCatalog().then(c=>{setCatalog(c);if(c.length){const first=c.find(s=>s.name.toLowerCase()==='sidr')??c[0];setSource(first.id);setStep(Math.floor(first.totalSteps/2));}})},[isTest]);
 useEffect(()=>{if(!isTest)return;let active=true;let timer:number|undefined;const load=()=>{void fetchStrikeVerification().then(v=>{if(!active)return;setVerif(v);if(v&&(v.state==='running'||v.state==='not_started'))timer=window.setTimeout(load,20_000)})};load();return()=>{active=false;if(timer)window.clearTimeout(timer)}},[isTest]);
 useEffect(()=>{let active=true;setLoading(true);setRisk(null);if(isTest&&!testStorm){setLoading(false);void fetchCoastalDistrictRoster().then(d=>{if(active&&d?.length)setRoster(d)});return()=>{active=false}}const req=testStorm?fetchDistrictRiskAnalysis(testStorm.id,step):fetchDistrictRiskAnalysis(cyclone?.id||'ACTIVE');void Promise.all([fetchCoastalDistrictRoster(),req]).then(([districts,result])=>{if(!active)return;if(districts?.length)setRoster(districts);setRisk(result?.stormId&&result.stormId!=='STANDBY'?result:null);setLoading(false);}).catch(()=>{if(active)setLoading(false)});return()=>{active=false}},[cyclone?.id,refresh,testStorm?.id,step,isTest]);
 const isReplay=risk?.mode==='replay';const actual=risk?.actualSummary;
 const assessments=new Map<string,DetailedDistrictRisk>(risk?.districts.map((d:DetailedDistrictRisk)=>[d.districtId,d] as [string,DetailedDistrictRisk])||[]);const sourceRoster=risk?.districts.length?risk.districts.map(d=>({id:d.districtId,name:d.districtName,state:d.state,centroid:d.centroid})):roster;
 const states=[...new Set(sourceRoster.map(d=>d.state))].sort();const rows=sourceRoster.filter(d=>(state==='ALL'||state===d.state)&&(level==='ALL'||assessments.get(d.id)?.warningLevel===level)&&`${d.name} ${d.state}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>((assessments.get(b.id)?.riskScore??-1)-(assessments.get(a.id)?.riskScore??-1))||a.name.localeCompare(b.name));
 return <div className="public-warnings">{!isTest&&<DashboardHero kicker="WARNINGS & PREPAREDNESS" title={'Know what’s ahead.\nPrepare with confidence.'} text="Find your coastal district, understand the information available, and follow official local guidance." actionLabel="Find your district" targetId="district-directory"/>}<div className="public-source-note" role="status"><Info size={20}/><div><strong>{loading?'Checking for district assessments…':risk?'Research assessment available':'Current district assessments are unavailable'}</strong><p>{risk?(isReplay?`Replay of test storm ${risk.stormName}: the forecast the model made on ${fmtTime(risk.issuedAt)}${risk.replay?` (time ${risk.replay.step+1} of ${risk.replay.totalSteps})`:''}, next to what the storm really did. The model never saw this storm in training.`:`Model output for ${risk.stormName}. This is not an official warning bulletin.`):isTest?(testStorm?'Loading the test-storm forecast…':'Test-storm data is not installed on the server.'):<>No active cyclone right now, so there is no live assessment. You can still explore the coastal district directory; to see how the model performed on past storms, open <Link to="/dashboard/test-strike" className="standby-test-link">District Strike Rate (Test Storms)</Link>. Missing data does not mean there is no risk.</>}</p>{!risk&&!isTest&&!loading?<Link to="/dashboard/test-strike" className="source-note-action">Open District Strike Rate (Test Storms) <ArrowUpRight size={14}/></Link>:null}</div><button onClick={()=>setRefresh(r=>r+1)} disabled={loading}><RefreshCw size={15}/>Refresh</button></div>
 <section className="warning-explainer"><div className="section-intro"><span className="eyebrow">A LITTLE CONTEXT GOES A LONG WAY</span><h2>Understand the warning colours.</h2><p>These categories explain the research model’s assessment. Always read the official advisory for your location.</p></div><div className="warning-tier-grid">{tiers.map(t=><button key={t.key} className={`warning-tier tier-${t.key.toLowerCase()} ${level===t.key?'chosen':''}`} aria-pressed={level===t.key} onClick={()=>setLevel(level===t.key?'ALL':t.key)}><div><span className="tier-dot"/><strong>{t.title}</strong><span className="tier-count">{risk?risk.districts.filter(d=>d.warningLevel===t.key).length:'—'}</span></div><h3>{t.label}</h3><p>{t.description}</p><span className="tier-foot">{risk?'View assessed districts':'Assessment data unavailable'}<ArrowUpRight size={15}/></span></button>)}</div></section>
 <div className="public-warning-columns"><section className="district-panel" id="district-directory"><div className="directory-heading"><div><span className="eyebrow">LOCAL INFORMATION</span><h2>Find your coastal district</h2><p>Search by district or state to see available assessments.</p></div><MapPin size={25}/></div><div className="district-controls"><label className="district-search"><Search size={17}/><input aria-label="Search district or state" placeholder="Search district or state…" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Filter by state" value={state} onChange={e=>setState(e.target.value)}><option value="ALL">All coastal states</option>{states.map(s=><option key={s}>{s}</option>)}</select><select aria-label="Filter by model tier" value={level} onChange={e=>setLevel(e.target.value)}><option value="ALL">All model tiers</option>{['RED','ORANGE','YELLOW','GREEN'].map(t=><option key={t} value={t}>{t.toLowerCase()}</option>)}</select>{isTest&&catalog.length>0&&<select aria-label="Choose test storm" value={source} onChange={e=>{const s=catalog.find(c=>c.id===e.target.value);setSource(e.target.value);setStep(s?Math.floor(s.totalSteps/2):0)}}>{catalog.map(s=><option key={s.id} value={s.id}>Test storm: {stormLabel(s)}</option>)}</select>}</div>
 {testStorm&&<div className="district-controls" style={{alignItems:'center',fontSize:11,color:'#4a6a7c'}}><span>Forecast time</span><input type="range" aria-label="Forecast time in the storm's life" min={0} max={Math.max(0,testStorm.totalSteps-1)} value={step} onChange={e=>setStep(Number(e.target.value))} style={{flex:1,minWidth:160}}/><span>{risk?.issuedAt?fmtTime(risk.issuedAt):`${step+1} / ${testStorm.totalSteps}`}</span></div>}
 <div className="district-table-wrap"><table><caption className="sr-only">Coastal district directory and available model assessments</caption><thead><tr><th>District / State</th><th>Model tier</th><th>Strike chance (24 h)</th><th>Closest approach</th><th>Est. wind</th>{isReplay&&<th>What really happened (24 h)</th>}</tr></thead><tbody>{rows.map(d=>{const a=assessments.get(d.id);return <tr key={d.id}><td><strong>{d.name}</strong><small>{d.state}</small></td><td><span className={`district-badge ${a?'badge-'+a.warningLevel.toLowerCase():''}`}>{a?`${a.warningLevel.toLowerCase()} tier`:'Not available'}</span></td><td>{a?.strikeLabel??'—'}</td><td>{a?`${Math.round(a.distanceKm)} km at +${a.closestHour} h`:'—'}</td><td>{a?.estimatedWindKts!=null?`${a.estimatedWindKts} knots`:'—'}</td>{isReplay&&<td>{a?.actualHit?<strong>{actualText(a)}</strong>:actualText(a)}</td>}</tr>})}</tbody></table>{!rows.length&&<div className="directory-empty"><Search size={24}/><h3>No matching districts</h3><p>Try another district, state or model tier.</p><button onClick={()=>{setSearch('');setState('ALL');setLevel('ALL')}}>Clear filters</button></div>}</div><div className="directory-footer">{rows.length} districts shown <span>{isReplay&&actual?`Reality: ${actual.districtsHit} district${actual.districtsHit===1?'':'s'} hit in ${actual.windowHours} h${actual.districtsHit?` (${actual.hitsWithOrangeOrRed} had orange/red, ${actual.hitsWithYellowOrAbove} yellow or higher)`:''} · ${actual.orangeOrRedHit} of ${actual.orangeOrRedDistricts} orange/red districts were hit${actual.trackComplete?'':' · real track ends before 24 h'}`:risk?'Research model output':'Directory only · no current assessment'}</span></div></section>
 <aside className="preparedness-panel"><div className="preparedness-art" aria-hidden="true"><House size={56} strokeWidth={1}/><span className="art-sun"/><span className="art-wave"/></div><span className="eyebrow">SMALL STEPS. BETTER PREPARED.</span><h2>Make a plan<br/>before you need it.</h2><p>Keep trusted information and essential items within reach.</p><div className="preparation-item"><Radio size={21}/><div><h3>Choose trusted updates</h3><p>Follow IMD and your local disaster management authority.</p></div></div><div className="preparation-item"><Backpack size={21}/><div><h3>Keep essentials together</h3><p>Make important documents, regular medicines and emergency contacts easy to find.</p></div></div><a href="https://ndma.gov.in/Natural-Hazards/Cyclone" target="_blank" rel="noreferrer">Read NDMA cyclone guidance <ArrowUpRight size={17}/></a></aside></div>
 {isTest&&<section className="district-panel" style={{marginTop:26}} aria-label="How reliable are the strike percentages"><div className="directory-heading"><div><span className="eyebrow">CHECKED AGAINST REALITY</span><h2>How reliable are these percentages?</h2><p>Every forecast the model made for the unseen 2021-23 and 2025 test storms, compared with whether the real storm centre passed within {verif?.data?.radiusKm??100} km of each district in the next {verif?.data?.windowHours??24} h (IBTrACS best track, IMD RSMC New Delhi).</p></div><Info size={25}/></div>
 {verif?.data?.available?<><div className="district-table-wrap"><table><caption className="sr-only">Strike probability reliability on test storms</caption><thead><tr><th>Model said</th><th>District forecasts</th><th>Average forecast</th><th>Actually hit</th><th>Real hit rate</th></tr></thead><tbody>{verif.data.bins.map(b=><tr key={b.label}><td><strong>{b.label}</strong></td><td>{b.forecasts.toLocaleString()}</td><td>{pct(b.meanPredicted)}</td><td>{b.hits}</td><td><strong>{pct(b.observedFrequency)}</strong></td></tr>)}</tbody></table></div>
 {verif.data.thresholds?.length?<div className="district-table-wrap" style={{borderTop:'1px solid #e0ebef'}}><table><caption className="sr-only">Warning performance by tier</caption><thead><tr><th>Warn when chance is</th><th>Correct warnings</th><th>False alarms</th><th>Missed hits</th><th>Precision</th><th>Recall (hits caught)</th><th>F1</th></tr></thead><tbody>{verif.data.thresholds.map(t=><tr key={t.threshold}><td><strong>{t.label}</strong></td><td>{t.tp}</td><td>{t.fp}</td><td>{t.fn}</td><td>{pct(t.precision)}</td><td>{pct(t.recall)}</td><td><strong>{t.f1!=null?t.f1.toFixed(2):'—'}</strong></td></tr>)}</tbody></table></div>:null}
 <div className="directory-footer"><span>{verif.data.storms} storms · {verif.data.forecastTimes} forecast times · {verif.data.pairs.toLocaleString()} district forecasts · {verif.data.hits} real hits</span><span>{verif.data.detectedYellowOrAbove} of {verif.data.hits} hits had yellow or higher · {verif.data.orangeOrRedCorrect} of {verif.data.orangeOrRedForecasts} orange/red forecasts were hit · Brier skill vs climatology {verif.data.brierSkill!=null?`${Math.round(100*verif.data.brierSkill)}%`:'—'}</span></div></>
 :<div className="directory-empty"><Info size={24}/><h3>{verif?.state==='running'||verif?.state==='not_started'?'Being calculated on the server':'Not available'}</h3><p>{verif?.state==='running'||verif?.state==='not_started'?'The check runs once after each update (a few minutes); this page refreshes it automatically.':verif?.data?.reason||verif?.error||'Test-storm data or models are not installed on the server.'}</p></div>}</section>}
 <section className="public-faq"><span className="eyebrow">GOOD QUESTIONS, CLEAR ANSWERS</span><h2>Understanding this page</h2>{[['Is this an official cyclone warning?','No. Cyclone AI is an independent research platform. Its model assessments support exploration and do not replace advisories from IMD or your local authority.'],['What does the strike chance mean?','It is the share of 1,000 simulated tracks (the forecast plus the model’s own past errors) in which the storm centre passes within 100 km of the district in the next 24 hours. It does not include storm surge, rain or wind extent.'],['What does “Not available” mean?','A current model assessment was not received for that district. It is not an all-clear or a statement that conditions are safe.'],['How do you know the percentages are right?','A single forecast can only be checked as yes or no: the storm came within 100 km or it did not. So the percentages are checked over many forecasts. For the 2021-23 and 2025 test storms, which the model never saw, the reliability table on the District Strike Rate (Test Storms) page groups every district forecast by what the model said and shows how often the storm really came within 100 km. Honest percentages show a real hit rate close to the forecast.'],['Why can the forecast change?','New observations can change the estimated track and intensity. Check the issue time and follow updates rather than relying on a single forecast.']].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section></div>
}
